/** CREATE RESELLER STAGING TABLE **/
CREATE TABLE "IMT577_DW_RUTH_YAWATA"."PUBLIC"."STAGE_RESELLER" ("RESLLERID" STRING NOT NULL, "CONTACT" VARCHAR (255) NOT NULL, "EMAILADDRESS" VARCHAR (255) NOT NULL, "ADDRESS" VARCHAR (255) NOT NULL, "CITY" VARCHAR (255) NOT NULL, "STATEPROVINCE" VARCHAR (255) NOT NULL, "COUNTRY" VARCHAR (255) NOT NULL, "POSTALCODE" INTEGER NOT NULL, "PHONENUMBER" STRING NOT NULL, "CREATEDDATE" STRING NOT NULL, "CREATEDBY" VARCHAR (255) NOT NULL, "MODIFIEDDATE" STRING, "MODIFIEDBY" VARCHAR (255), "RESELLERNAME" VARCHAR (255) NOT NULL);
/** CREATE SALES DETAIL STAGING TABLE **/
CREATE TABLE "IMT577_DW_RUTH_YAWATA"."PUBLIC"."STAGE_SALESDETAIL" ("SALESDETAILID" INTEGER NOT NULL, "SALESHEADERID" INTEGER NOT NULL, "PRODUCTID" INTEGER NOT NULL, "SALESQUANTITY" INTEGER NOT NULL, "SALESAMOUNT" FLOAT NOT NULL, "CREATEDDATE" STRING NOT NULL, "CREATEDBY" VARCHAR (255) NOT NULL, "MODIFIEDDATE" STRING, "MODIFIEDBY" VARCHAR (255));
/** CREATE SALES HEADER STAGING TABLE **/
CREATE TABLE "IMT577_DW_RUTH_YAWATA"."PUBLIC"."STAGE_SALESHEADER" ("SALESHEADERID" INTEGER NOT NULL, "DATE" STRING NOT NULL, "CHANNELID" INTEGER NOT NULL, "STOREID" INTEGER, "CUSTOMERID" STRING, "RESELLERID" STRING, "CREATEDDATE" STRING NOT NULL, "CREATEDBY" VARCHAR (255) NOT NULL, "MODIFIEDDATE" STRING, "MODIFIEDBY" VARCHAR (255));
/** CREATE STORE STAGING TABLE **/
CREATE TABLE "IMT577_DW_RUTH_YAWATA"."PUBLIC"."STAGE_STORE" ("STOREID" INTEGER NOT NULL, "SUBSEGMENTID" INTEGER NOT NULL, "STORENUMBER" INTEGER NOT NULL, "STOREMANAGER" VARCHAR (255) NOT NULL, "ADDRESS" VARCHAR (255) NOT NULL, "CITY" VARCHAR (255) NOT NULL, "STATEPROVINCE" VARCHAR (255) NOT NULL, "COUNTRY" VARCHAR (255) NOT NULL, "POSTALCODE" INTEGER NOT NULL, "PHONENUMBER" STRING NOT NULL, "CREATEDDATE" STRING NOT NULL, "CREATEDBY" VARCHAR (255) NOT NULL, "MODIFIEDDATE" STRING, "MODIFIEDBY" VARCHAR (255));
/** CREATE TARGET DATA CHANNEL STAGING TABLE **/
CREATE TABLE "IMT577_DW_RUTH_YAWATA"."PUBLIC"."STAGE_TARGETDATACHANNEL" ("YEAR" STRING NOT NULL, "CHANNELNAME" VARCHAR (255) NOT NULL, "TARGETNAME" VARCHAR(255) NOT NULL, "TARGETSALESAMOUNT" FLOAT NOT NULL)
/** CREATE TARGET DATA PRODUCT STAGING TABLE **/
CREATE TABLE "IMT577_DW_RUTH_YAWATA"."PUBLIC"."STAGE_TARGETDATAPRODUCT" ("PRODUCTID" INTEGER NOT NULL, "PRODUCT" VARCHAR (255) NOT NULL, "YEAR" STRING NOT NULL, "SALESQUANTITYTARGET" FLOAT NOT NULL)

